import { Prisma } from '@prisma/client';
import { NextResponse } from 'next/server';
import { z } from 'zod';

import { ForbiddenError, UnauthorizedError } from '@/server/common/error';
import { requireUser } from '@/server/auth/authorization';
import { prisma } from '@/server/db/prisma';

const startVerificationSchema = z.object({
  invoiceNumber: z
    .string()
    .trim()
    .min(1, 'Invoice number is required')
    .max(100, 'Invoice number is too long'),

  invoicedQuantity: z
    .number()
    .int('Invoiced quantity must be a whole number')
    .positive('Invoiced quantity must be greater than zero'),

  invoicedWeight: z
    .number()
    .positive('Invoiced weight must be greater than zero'),
});

export async function POST(request: Request) {
  try {
    /*
     * ---------------------------------------------------------
     * Authentication
     * ---------------------------------------------------------
     */

    const supervisor = await requireUser();

    /*
     * Only supervisors can start invoice verification.
     */
    if (supervisor.role !== 'SUPERVISOR') {
      throw new ForbiddenError();
    }

    /*
     * A supervisor must belong to a company.
     */
    if (!supervisor.companyId) {
      return NextResponse.json(
        {
          error: 'Your account is not assigned to a company.',
        },
        { status: 400 },
      );
    }

    /*
     * ---------------------------------------------------------
     * Validate request body
     * ---------------------------------------------------------
     */

    const body = await request.json();

    const validation = startVerificationSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: validation.error.flatten().fieldErrors,
        },
        { status: 400 },
      );
    }

    const { invoiceNumber, invoicedQuantity, invoicedWeight } = validation.data;

    /*
     * ---------------------------------------------------------
     * Check for an existing active verification
     *
     * A supervisor can only verify one invoice at a time.
     * ---------------------------------------------------------
     */

    const activeVerification = await prisma.invoiceVerification.findFirst({
      where: {
        supervisorId: supervisor.id,
        status: 'ACTIVE',
      },
      select: {
        id: true,
        invoiceNumber: true,
        startedAt: true,
      },
    });

    if (activeVerification) {
      return NextResponse.json(
        {
          error:
            'You must complete your current invoice verification before starting another one.',
          verification: activeVerification,
        },
        { status: 409 },
      );
    }

    /*
     * ---------------------------------------------------------
     * Create verification
     *
     * startedAt is generated by the SERVER.
     * ---------------------------------------------------------
     */

    const verification = await prisma.invoiceVerification.create({
      data: {
        invoiceNumber,
        invoicedQuantity,
        invoicedWeight: new Prisma.Decimal(invoicedWeight),

        /*
         * These are deliberately left NULL.
         * The supervisor enters them when completing
         * the verification.
         */
        dispatchedQuantity: null,
        dispatchedWeight: null,
        remarks: null,
        result: null,

        status: 'ACTIVE',
        startedAt: new Date(),

        supervisorId: supervisor.id,
        companyId: supervisor.companyId,
      },
      select: {
        id: true,
        invoiceNumber: true,
        invoicedQuantity: true,
        invoicedWeight: true,
        status: true,
        startedAt: true,
        supervisorId: true,
        companyId: true,
        createdAt: true,
      },
    });

    /*
     * ---------------------------------------------------------
     * Return active verification
     * ---------------------------------------------------------
     */

    return NextResponse.json(
      {
        success: true,
        verification: {
          id: verification.id,
          invoiceNumber: verification.invoiceNumber,
          invoicedQuantity: verification.invoicedQuantity,
          invoicedWeight: verification.invoicedWeight.toString(),
          status: verification.status,
          startedAt: verification.startedAt,
          supervisorId: verification.supervisorId,
          companyId: verification.companyId,
          createdAt: verification.createdAt,
        },
      },
      { status: 201 },
    );
  } catch (error) {
    if (error instanceof UnauthorizedError) {
      return NextResponse.json(
        {
          error: 'Authentication required',
        },
        { status: 401 },
      );
    }

    if (error instanceof ForbiddenError) {
      return NextResponse.json(
        {
          error: 'Only supervisors can start invoice verifications.',
        },
        { status: 403 },
      );
    }

    /*
     * Duplicate invoice.
     *
     * The database has a unique constraint on:
     * companyId + invoiceNumber
     */
    if (
      error instanceof Prisma.PrismaClientKnownRequestError &&
      error.code === 'P2002'
    ) {
      return NextResponse.json(
        {
          error: 'This invoice has already been verified for your company.',
        },
        { status: 409 },
      );
    }

    console.error('Create invoice verification error:', error);

    return NextResponse.json(
      { error: 'Something went wrong' },
      { status: 500 },
    );
  }
}

export async function GET() {
  try {
    const supervisor = await requireUser();

    if (supervisor.role !== 'SUPERVISOR') {
      throw new ForbiddenError();
    }

    const verification = await prisma.invoiceVerification.findFirst({
      where: {
        supervisorId: supervisor.id,
        status: 'ACTIVE',
      },
      select: {
        id: true,
        invoiceNumber: true,
        invoicedQuantity: true,
        invoicedWeight: true,
        dispatchedQuantity: true,
        dispatchedWeight: true,
        remarks: true,
        result: true,
        status: true,
        startedAt: true,
        completedAt: true,
        createdAt: true,
      },
    });

    return NextResponse.json({
      data: verification
        ? {
            ...verification,
            invoicedWeight: verification.invoicedWeight.toString(),
            dispatchedWeight: verification.dispatchedWeight?.toString() ?? null,
          }
        : null,
    });
  } catch (error) {
    if (error instanceof UnauthorizedError) {
      return NextResponse.json(
        { error: 'Authentication required' },
        { status: 401 },
      );
    }

    if (error instanceof ForbiddenError) {
      return NextResponse.json(
        { error: 'Only supervisors can access invoice verifications.' },
        { status: 403 },
      );
    }

    console.error('Get invoice verification error:', error);

    return NextResponse.json(
      { error: 'Something went wrong' },
      { status: 500 },
    );
  }
}
